### PR TITLE
Search bar & responsiveness

### PR DESCRIPTION
**Pull request by chengtianyue**
1, Added search bar highlight using arrows
2, navbar responsiveness

### CODE REVIEW

**Comment by chenyx512** [comment]
@Miclin1024 btw the current method of searching after change seems buggy, like when typing a word fast it may turn out some wierd results. Should we limit the maximum request frequency, or request periodically whenever the search bar is in focus?

**Comment by Miclin1024** [comment]
> @Miclin1024 btw the current method of searching after change seems buggy, like when typing a word fast it may turn out some wierd results. Should we limit the maximum request frequency, or request periodically whenever the search bar is in focus?

Yeah I'm guessing it's because the ajax requests for fetching search results take different networking times to complete (request sending out early ended up taking longer and therefore finished after newer requests). Setting a _blackout time_ longer than the networking time after each request should fix the problem. @chengtianyue you wanna try to do this?

**Review by Miclin1024 — CHANGES_REQUESTED** [review]
These changes look good. One small thing I would say tho is that the red highlight color feels kinda off. Maybe consider changing it to some sort of lowkey grey?

**Review by Miclin1024 — APPROVED** [review]
Great work! Let's merge it to dev.

**Comment by chengtianyue** [comment]
@Miclin1024 OK!

**Pull request merged**
