### PR TITLE
Unregistered index responsive

### PR DESCRIPTION
**Pull request by chengtianyue**

### CODE REVIEW

**Comment by Miclin1024** [comment]
Some of the views may be too large on a larger screen

**Review by Miclin1024 — CHANGES_REQUESTED** [review]
Nice start! One thing I'd say is that instead of stretching all the images and text into one column, which seems to make content way too big on a larger device, you should keep the old layout for the large viewport (2 columns of image + text). And then switch to one column on smaller devices (678px). You can use **Bootstrap grid** if you want (something like `col-sm-12 col-6`) since that's already been integrated with `base.html`, or you can use CSS media query with flexbox.

**Comment by chenyx512** [comment]
@chengtianyue I would suggest using bootstrap grid throughout may be a good idea, since it used in some other templates as well.

**Comment by chengtianyue** [comment]
Got it!

**Comment by chengtianyue** [comment]
@Miclin1024 Hi. Now the image problem has solved. Ready for review.

**Comment by chenyx512** [comment]
@Miclin1024 Do we have a general guideline for containers in general, as they would be needed for other pages as well. Consider adding some guidelines to the "design guideline" Feishu doc in the webdev folder.

**Comment by Miclin1024** [comment]
I can make wrapper CSS classes for flexbox in main. But I think it wouldn't be that easy to use without a general understanding of flexbox and flow layout. Maybe we should arrange a meeting at some point to walk through the concepts?

**Pull request merged**
